---

- name: octoprint | Configure camera
  become: true
  template:
    src: "templates/octopi.txt.j2"
    dest: "/boot/octopi.txt"
    mode: 0755
  when: camera_usb_options is defined
  tags: camera
