---

- name: Ensure latest oprint pip
  pip:
    executable: ~/oprint/bin/pip
    name: pip
    state: latest
  tags: [ never, update ]

- include_tasks: plugins.yml
  tags: plugins

- include_tasks: camera.yml
  tags: camera

- include_tasks: printer.yml
  tags: printer

- name: Copy GCode scripts
  copy:
    src: "{{ item }}"
    dest: ~/.octoprint/scripts/gcode/
    mode: 0644
  with_fileglob:
    - files/scripts/gcode/*
  notify:
    - Restart octoprint service
  tags: config
