---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags: [ never, update ]

- include_tasks: plugins.yml
  tags: plugins

- include_tasks: camera.yml
  tags: camera

- include_tasks: printer.yml
  tags: printer
