---

- name: octoprint | Install plugins
  pip:
    executable: ~/oprint/bin/pip
    name: "git+{{ item.repo }}@{{ item.release }}"
  with_items: "{{ octoprint_plugins }}"
  when: octoprint_plugins is defined
  tags: plugins
