language: python
python:
  - "3.7"
install:
  - pip --quiet install ansible
before_script:
  - ansible-playbook --version
  - ansible-galaxy role install -r requirements.yml
script:
  - ansible-playbook --inventory tests/inventory --syntax-check xennis-home.yml
branches:
  only: [master]
