---

- name: Xennis OctoPi
  hosts: octopi
  user: pi
  roles:
    - system
    - octoprint

- name: Xennis raspotify
  hosts: raspotify
  user: pi
  roles:
    - role: system
      vars:
        amixer_simple_control_id: "PCM"
        amixer_volume: "100%"
    - role: xennis.raspotify
      become: yes
      vars:
        device_name: "XennisPi"
