---

- name: Xennis OctoPi
  hosts: octopi
  user: pi
  roles:
    - system
    - octoprint

- name: Xennis raspotify
  hosts: raspotify
  user: pi
  roles:
    - role: xennis.raspotify
      become: yes
      vars:
        device_name: "XennisPi"
