name: Ansible
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: pip --quiet install ansible
    - run: |
        ansible-playbook --version
        ansible-galaxy role install -r requirements.yml
    - run: ansible-playbook --inventory tests/inventory --syntax-check xennis-home.yml
